### ISSUE TITLE
/elytra mixed with void

### ISSUE THREAD

**Issue by RileyDatLord** [Minehut/Issues#231] opened 2017-07-16 07:03 UTC
### Expected behavior
Teleport back to spawn.

### Actual behavior
Teleports to spawn. but spams tp and playsounds me, unable to move.

### Detailed steps to reproduce this behavior
1. Use /elytra to get a eltra
2. Fly into the void.

### Server name
Lobby (1 / 2 / 3)

### Link to server logs (/dl log)
N/A

**Comment by MatrixTunnel** [comment] 2017-07-16 07:25
Duplicate of #184

**Closed by MatrixTunnel** 2017-07-16 07:25 UTC
