### ISSUE TITLE
Server ProtocalLib error

### ISSUE THREAD

**Issue by iKarTehFox** [Minehut/Issues#41] opened 2017-06-09 01:35 UTC
When I started up my server on 1.12, it started to tell me that 'It is unable to inject incoming channel'. Here's a picture.

![error](https://user-images.githubusercontent.com/17345571/26957331-ec6063cc-4c89-11e7-8e84-e22e10b94c9e.PNG)

**Comment by MatrixTunnel** [comment] 2017-06-09 03:20
I updated ProtocolLib which I think was the cause. If the error continues, send another message here

**Comment by karaoke60000** [comment] 2017-06-09 16:03
It's still saying it.

**Comment by lukechatton** [comment] 2017-06-09 16:55
I just rolled out a spigot update. Could you restart your server and test again? @karaoke60000

**Comment by MatrixTunnel** [comment] 2017-06-09 17:00
It's a bug with ProtocolLib. I checked their GitHub and other people are having the same problem

**Comment by MatrixTunnel** [comment] 2017-06-09 20:19
They released an update for it and it should be fixed. Let us know if it still does it :)

**Comment by karaoke60000** [comment] 2017-06-09 22:04
Sorry for not responding to your message. It still says it.

**Comment by MatrixTunnel** [comment] 2017-06-09 23:48
It's ok! Try restarting your server 3 times and report back if it works then or not :)

**Comment by karaoke60000** [comment] 2017-06-10 14:35
I just joined my server, it started to flood my chat with errors, then the closed the server down by itself...

**Comment by karaoke60000** [comment] 2017-06-10 14:38
The server doesn't close down anymore, just so you know.

**Comment by lukechatton** [comment] 2017-06-10 15:25
Just to confirm, you are saying the issue is resolved now?

**Comment by karaoke60000** [comment] 2017-06-10 15:40
No

**Comment by Trophonix** [comment] 2017-06-10 21:29
@karaoke60000 This issue should now be fixed.

**Comment by karaoke60000** [comment] 2017-06-10 21:36
For me, it seems to still pop up... I'm stumped...

**Comment by MatrixTunnel** [comment] 2017-06-10 22:12
@karaoke60000 What plugins are you running on your server? I think it might be one of the plugins that uses ProtocolLib

**Comment by karaoke60000** [comment] 2017-06-10 22:36
Does NCP use ProtocoLib?

**Comment by MatrixTunnel** [comment] 2017-06-10 23:21
Yes. That hasn't been updated yet so that might be part of the problem

**Comment by iKarTehFox** [comment] 2017-06-10 23:27
@MatrixTunnel I don't have NCP, I noticed that. Which of my plugins are erroring?

**Comment by MatrixTunnel** [comment] 2017-06-17 16:34
Since nothing has been reported in the past week, I'm going to consider this resolved

**Closed by MatrixTunnel** 2017-06-17 16:34 UTC
Labels: bug, mc
