### ISSUE TITLE
Tier Plugins still not work

### ISSUE THREAD

**Issue by HaZePug** [Minehut/Issues#185] opened 2017-07-03 17:34 UTC
### Expected behavior
Install a tier plugin

### Actual behavior
Says dont have a rank

### Server name
TaZerPrison

**Comment by tjhubz** [comment] 2017-07-03 19:37
Dupe of #122, @MatrixTunnel can fix it

**Comment by MatrixTunnel** [comment] 2017-07-06 00:55
Fixed :)

**Closed by MatrixTunnel** 2017-07-06 00:55 UTC
