### ISSUE TITLE
Tier 2 Not working

### ISSUE THREAD

**Issue by ItzMelonMatt** [Minehut/Issues#169] opened 2017-07-01 11:10 UTC
### Expected behavior
I was suppose to get every tier 1 and tier 2

### Actual behavior
it tells me that I need to purchase a tier

### Detailed steps to reproduce this behavior
--
### Server name
Planetary-Prison

### Link to server logs (/dl log)
--

**Comment by MatrixTunnel** [comment] 2017-07-01 20:00
Dupe of #122

**Closed by MatrixTunnel** 2017-07-01 20:00 UTC
