### ISSUE TITLE
No response from commands

### ISSUE THREAD

**Issue by Bayside308** [Minehut/Issues#147] opened 2017-06-25 02:03 UTC
### Expected behavior
Commands should execute as intended, from /sethome to /minehut.

### Actual behavior
No commands seem to work. There is no output given. I am unable to supply logs, as that command is also broken.

### Detailed steps to reproduce this behavior
Originally, I thought that the issue was the command.yml editor. However, this does not appear to be the cause, but instead a side-effect. It seems to just happen sporadically.

### Server name
Bukkit

### Link to server logs (/dl log)
Unable to access.

**Comment by BennyDoesTheStuff** [comment] 2017-06-25 02:36
hmm, seems like I'm also having a similar issue, I think a plugin is causing this to happen as unlike you I can do /minehut and /dl but can't really do any other commands.
Here is the log I was able to upload:
https://transfer.sh/uDs3C/latest.log

**Comment by lukechatton** [comment] 2017-06-25 03:07
Looks like it was traced back to these Essentials startup errors. 

```
[02:33:00] [Server thread/INFO]: [Player Join] {id=566a0259762ce5588f2fddf0, name=BennyDoesStuff, rank=PRO, server=566a0277762ce5588f2fddf1}
[02:33:00] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_12_R1.ChatSerializer
[02:33:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[02:33:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[02:33:00] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[02:33:00] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[02:33:00] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[02:33:00] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[02:33:00] [Server thread/WARN]: 	at com.sn1cko.tablist.methods.theTablist.getNmsClass(theTablist.java:18)
[02:33:00] [Server thread/WARN]: 	at com.sn1cko.tablist.methods.theTablist.sendTablist(theTablist.java:66)
[02:33:00] [Server thread/WARN]: 	at com.sn1cko.tablist.events.playerJoin.onJoin(playerJoin.java:41)
[02:33:00] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:33:00] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:33:00] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:33:00] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[02:33:00] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[02:33:00] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[02:33:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
[02:33:00] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[02:33:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:342)
[02:33:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:162)
[02:33:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159)
[02:33:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57)
[02:33:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233)
[02:33:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140)
[02:33:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842)
[02:33:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[02:33:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[02:33:00] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[02:33:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[02:33:00] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Essentials v2.0.1-b483
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:342) [spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:162) [spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:842) [spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: com/earth2me/essentials/EssentialsPlayerListener$1
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerJoin(EssentialsPlayerListener.java:176) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	... 14 more
Caused by: java.lang.ClassNotFoundException: com.earth2me.essentials.EssentialsPlayerListener$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerJoin(EssentialsPlayerListener.java:176) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.9.jar:git-Spigot-4df3c0c-03f1e37]
	... 14 more
```

@BennyDoesTheStuff, was your server freshly reset? Could you try and re-install Essentials? I believe the issue is that only the Plugin Collection version of Essentials was updated, but the "template" server folder still has the old version of Essentials in it. That was a bad design choice on my part.

**Comment by BennyDoesTheStuff** [comment] 2017-06-25 17:22
Yea, seems that fixed that right up when I updated essentials. One possible feature to implement related to this would be to send the owner a message whenever a plugin needs updating every time they join their server back.

**Comment by Trophonix** [comment] 2017-06-29 21:30
This should be fixed now.

**Closed** 2017-06-30 22:03 UTC
